process.env.NODE_ENV = "test";
process.env.PORT = "4001";
process.env.DATABASE_URL = process.env.DATABASE_URL ?? "postgresql://postgres:postgres@localhost:5432/prepos_test?schema=public";
process.env.REDIS_URL = process.env.REDIS_URL ?? "redis://localhost:6379";
process.env.JWT_ACCESS_SECRET = "test-access-secret-at-least-16";
process.env.JWT_REFRESH_SECRET = "test-refresh-secret-at-least-16";
process.env.JWT_ACCESS_EXPIRES_IN = "15m";
process.env.JWT_REFRESH_EXPIRES_IN = "30d";
process.env.CORS_ORIGIN = "http://localhost:3000";
process.env.RATE_LIMIT_WINDOW_MS = "60000";
process.env.RATE_LIMIT_MAX_REQUESTS = "1000";
